In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
# Sample Documents
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important ofr keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [ ]:
query="keyword-based search"

In [ ]:
import re

def preprocess_text(text):
    # Convert text to lowercase
    text=text.lower()
    # Remove puncutation
    text=re.sub(r'[^a-z0-9\s]','',text)
    return text


In [ ]:
[preprocess_text(doc) for doc in documents]

['this is a list which containing sample documents',
 'keywords are important ofr keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [ ]:
print("Preprocessed Query:")
print(query)

Preprocessed Query:
keyword-based search


In [ ]:
preprocessed_query = preprocess_text(query)

In [ ]:
preprocessed_query

'keywordbased search'

In [ ]:
vector=TfidfVectorizer()

In [ ]:
X = vector.fit_transform(documents)

In [ ]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.37796447, 0.        ,
        0.37796447, 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.        , 0.37796447, 0.        , 0.        ,
        0.37796447, 0.37796447],
       [0.        , 0.42693074, 0.3365971 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.42693074, 0.        ,
        0.        , 0.3365971 , 0.3365971 , 0.        , 0.42693074,
        0.        , 0.        , 0.        , 0.3365971 , 0.        ,
        0.        , 0.        ],
       [0.46516193, 0.        , 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.46516193, 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.32555709, 0.        , 0.        ,
        0.       

In [ ]:
X.toarray()[0]

array([0.        , 0.        , 0.        , 0.37796447, 0.        ,
       0.37796447, 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.        , 0.37796447, 0.        , 0.        ,
       0.37796447, 0.37796447])

In [ ]:
query_embedding = vector.transform([preprocessed_query])

In [ ]:
query_embedding.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0.]])

In [ ]:
similarities = cosine_similarity(X, query_embedding)

In [ ]:
similarities

array([[0.        ],
       [0.3365971 ],
       [0.        ],
       [0.32555709]])

In [ ]:
np.argsort(similarities, axis=0)

array([[0],
       [2],
       [3],
       [1]])

In [ ]:
ranked_documents = [documents[i] for i in ranked_indices]


In [ ]:
# Ranking
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()


In [ ]:
ranked_indices

array([1, 3, 2, 0])

In [ ]:
ranked_indices

array([1, 3, 2, 0])

In [ ]:
# Output the ranked documents
for i, doc in enumerate(ranked_documents):
  print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important ofr keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: Document analysis involves extracting keywords.
Rank 4: This is a list which containing sample documents.


In [ ]:
query

'keyword-based search'

In [ ]:
document_embeddings = np.array([
    [0.634, 0.234, 0.867, 0.042, 0.249],
    [0.123, 0.456, 0.789, 0.321, 0.654],
    [0.987, 0.654, 0.321, 0.123, 0.456]
])

In [ ]:
# Sample search query (represented as a dense vector)
query_embedding = np.array([[0.789, 0.321, 0.654, 0.987, 0.123]])


In [ ]:
# Calcualte cosine similarity between query and documents
similarities = cosine_similarity(document_embeddings, query_embedding)


In [ ]:
ranked_indices = np.argsort(similarities, axis=0)[::-1].flatten()

In [ ]:
ranked_indices

array([0, 2, 1])

In [ ]:
# Output the ranked documents
for i, idx in enumerate(ranked_indices):
  print(f"Rank {i+1}: Document {idx+1}")

Rank 1: Document 1
Rank 2: Document 3
Rank 3: Document 2


In [ ]:
doc_path="/content/AI Intern Assignment 2.pdf"

In [ ]:
!pip install pypdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.8/295.8 kB 4.5 MB/s eta 0:00:00


In [ ]:
!pip install langchain_community

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 997.8/997.8 kB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 391.5/391.5 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 8.8 MB/s eta 0:00:00
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.0.0
    Uninstalling tenacity-9.0.0:
      Successfully uninstalled tenacity-9.0.0


In [ ]:
from langchain_community.document_loaders import PyPDFLoader

In [ ]:
loader = PyPDFLoader(doc_path)

In [ ]:
docs = loader.load()

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter


In [ ]:
splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=20)


In [ ]:
chunks = splitter.split_documents(docs)


In [ ]:
chunks

[Document(metadata={'source': '/content/AI Intern Assignment 2.pdf', 'page': 0}, page_content='Retrieval\nAugmented\nGeneration(RAG)\nin\nLLM\nSection\n1:\nTheoretical\nKnowledge\n1.1.\nBasics\nof\nRetrieval-Augmented\nGeneration\n(RAG)\nQuestion:\nExplain\nthe\nconcept\nof\nRetrieval-Augmented\nGeneration\n(RAG).'),
 Document(metadata={'source': '/content/AI Intern Assignment 2.pdf', 'page': 0}, page_content='Generation\n(RAG).\nHow\ndoes\nit\ndiffer\nfrom\nstandard\ntext\ngeneration\nmethods\nin\nNLP?\n1.2.\nInformation\nRetrieval\nTechniques\nQuestion:What\nare\nDense\nPassage\nRetrieval\n(DPR)\nand\nSparse\nRetrieval?\nCompare'),
 Document(metadata={'source': '/content/AI Intern Assignment 2.pdf', 'page': 0}, page_content='Retrieval?\nCompare\ntheir\nstrengths\nand\nweaknesses.\n1.3.\nTransformer\nModels\nin\nNLP\n(10\nPoints)\nQuestion:\nBriefly\ndescribe\nthe\narchitecture\nof\nTransformer\nmodels\nand\ntheir\nrole\nin\nLLMs.\nHow\ndo\nthey'),
 Document(metadata={'source': '/cont

In [ ]:
from langchain.embeddings import HuggingFaceInferenceAPIEmbeddings


In [ ]:
HF_TOKEN="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"

In [ ]:
embeddings = HuggingFaceInferenceAPIEmbeddings(api_key=HF_TOKEN, model_name="BAAI/bge-base-en-v1.5")


In [ ]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 584.3/584.3 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 39.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.8/273.8 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 54.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 4.3 MB/s eta 0:00:00


In [ ]:
from langchain.vectorstores import Chroma

In [ ]:
vectorstore = Chroma.from_documents(chunks, embeddings)

In [ ]:
vectorstore_retriever = vectorstore.as_retriever(search_kwargs={"k": 3})


In [ ]:
vectorstore_retriever


VectorStoreRetriever(tags=['Chroma', 'HuggingFaceInferenceAPIEmbeddings'], vectorstore=<langchain_community.vectorstores.chroma.Chroma object at 0x7938aabdd330>, search_kwargs={'k': 3})

In [ ]:
!pip install rank_bm25

In [ ]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever


In [ ]:
keyword_retriever = BM25Retriever.from_documents(chunks)

In [ ]:
keyword_retriever.k = 3

In [ ]:
ensemble_retriever = EnsembleRetriever(
    retrievers=[vectorstore_retriever, keyword_retriever],
    weights=[0.3, 0.7]
)

hybrid_score = (1-alpha)*sparse_score + alpha * dense_score

In [ ]:
model_name = "HuggingFaceH4/zephyr-7b-beta"

In [ ]:
!pip install bitsandbytes

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
!pip install accelerate

In [ ]:
!pip install transformers

In [ ]:
import torch
from transformers import (AutoModelForCausalLM, AutoTokenizer, pipeline, BitsAndBytesConfig)
from langchain.llms import HuggingFacePipeline

In [ ]:
# function for loading 4-bit quantized model
def load_quantized_model(model_id: str):
  """
    model_name: Name or path of the model to be loaded.
    return: Loaded quantized model.
  """

  bnb_config = BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_use_double_quant=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_compute_dtype=torch.bfloat16

  )

  model = AutoModelForCausalLM.from_pretrained(
      model_id,
      quantization_config=bnb_config,
  )
  return model

In [ ]:
# initializing tokenizer
def initialze_tokenizer(model_name: str):
  tokenizer = AutoTokenizer.from_pretrained(model_name, return_token_type_ids=False)
  tokenizer.bos_token_id = 1 # Set beginning of sentence token id
  return tokenizer


In [ ]:
tokenizer = initialze_tokenizer(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

In [ ]:
model = load_quantized_model(model_name)


In [ ]:
pipeline = pipeline(
    "text-generation",
    model=model_name,
    tokenizer=tokenizer,
    use_cache=True,
    device_map="auto",
    max_length=2048,
    do_sample=True,
    top_k=5,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.eos_token_id,
)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [ ]:
llm=HuggingFacePipeline(pipeline=pipeline)

/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py:141: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 0.3. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFacePipeline`.
  warn_deprecated(


In [ ]:
from langchain.chains import RetrievalQA

In [ ]:
normal_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore_retriever,
    return_source_documents=True
)

In [ ]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=ensemble_retriever,
    return_source_documents=True
)

In [ ]:
response1

NameError: name 'response1' is not defined

In [ ]:
response1 = normal_chain.invoke("what is this document all about")


In [ ]:
print(response1.get("result"))