In [ ]:

documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [ ]:
!pip install sentence_transformers


  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
from sentence_transformers import SentenceTransformer


/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [ ]:

# Load pre-trained Sentence Transformer model
model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'

In [ ]:
model = SentenceTransformer(model_name)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.78k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/550 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
documents


['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [ ]:
len(documents)


8

In [ ]:
document_embeddings = model.encode(documents)


In [ ]:
len(document_embeddings)


8

In [ ]:
len(document_embeddings[0])


768

In [ ]:
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

Document 1 embedding: [ 0.10894687  0.07812072  0.11626563 -0.31912503  0.46890235  0.43514383
  0.01453741  0.44238755  0.29716393 -0.18982707  0.07389057 -0.27864924
  0.21338163 -0.12077013  0.17891704 -0.00789886  0.04754867 -0.1820457
  0.3422711  -0.0699426  -0.1428874   0.5714125  -0.11153242 -0.178954
  0.01523124  0.2610571  -0.20555837  0.05203113 -0.02810759  0.23873235
  0.01206979  0.04404923  0.02242314 -0.1389518  -0.7410037   0.25601006
  0.0814968   0.18820494 -0.4123769   0.11368617  0.2812116   0.05860877
 -0.17318784  0.33549133  0.2180369  -0.05090719 -0.05457786 -0.8738478
 -0.24082261  0.3200697   0.44761658  0.06347825  0.5357484   0.16607252
 -0.33196995  0.33393636  0.28615916 -0.5419566  -0.2713242   0.2488116
 -0.23919387 -0.46926287  0.13836573  0.37842885 -0.01304426  0.01990603
  0.32365084  0.45857546  0.07600262  0.25299576 -0.4293894   0.10051921
 -0.33042604 -0.6987646   0.01035907  0.05666569  0.14731242 -0.4708235
  0.08063989  0.33870456 -0.2727815

In [ ]:
documents


['This is a list which containing sample documents.',
 'Keywords are important for keyword-based search.',
 'Document analysis involves extracting keywords.',
 'Keyword-based search relies on sparse embeddings.',
 'Understanding document structure aids in keyword extraction.',
 'Efficient keyword extraction enhances search accuracy.',
 'Semantic similarity improves document retrieval performance.',
 'Machine learning algorithms can optimize keyword extraction methods.']

In [ ]:
query = "Natural language processing techniques enhance keyword extraction efficiency."


In [ ]:
query_embedding = model.encode(query)


In [ ]:
print("Query embedding:", query_embedding)


Query embedding: [ 3.42821062e-01  3.26170295e-01  7.73252780e-03  1.60759073e-02
  2.38516759e-02 -2.52880752e-01  8.15467983e-02  1.37177244e-01
  3.33291888e-01  3.65743488e-02 -9.28224847e-02 -3.43725741e-01
  7.12016448e-02  9.48833823e-01 -9.41288620e-02 -7.96414018e-01
 -3.20592076e-01 -2.67564565e-01  2.08664209e-01  7.99597651e-02
  7.93334842e-03 -5.22296950e-02 -1.00512743e-01 -2.04229847e-01
  2.19562739e-01  7.67739564e-02  1.25881493e-01  2.90843815e-01
 -4.99191105e-01  2.27709681e-01 -1.94742531e-01  7.21394718e-02
 -4.56507551e-03  1.21945664e-01 -1.46225601e-01 -9.64744911e-02
  1.02258198e-01 -2.04421133e-01 -3.95657837e-01  7.32252747e-02
  1.10104233e-01  4.84611213e-01  1.04519360e-01  3.86131734e-01
 -1.68697283e-01 -2.11251184e-01 -6.38036489e-01 -4.32641476e-01
  2.74459183e-01  9.64053199e-02 -1.30053610e-01  5.76567017e-02
  8.07964057e-02  6.48146942e-02 -2.14183563e-03  2.29773819e-01
 -6.66053742e-02  3.07675421e-01  2.11779565e-01 -1.57844454e-01
  9.7885

In [ ]:
len(query_embedding)


768

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarities = cosine_similarity(np.array([query_embedding]), document_embeddings)


In [ ]:
similarities


array([[0.16948149, 0.4580228 , 0.5675695 , 0.441233  , 0.6316118 ,
        0.75214136, 0.550352  , 0.74481666]], dtype=float32)

In [ ]:
most_similar_index = np.argmax(similarities)


In [ ]:
most_similar_index


5

In [ ]:
most_similar_document = documents[most_similar_index]


In [ ]:
most_similar_document


'Efficient keyword extraction enhances search accuracy.'

In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:
similarity_score = similarities[0][most_similar_index]


In [ ]:
similarity_score


0.75214136

In [ ]:
sorted_indices = np.argsort(similarities[0])[::-1]


In [ ]:
sorted_indices


array([5, 7, 4, 2, 6, 1, 3, 0])

In [ ]:
ranked_documents = [(documents[i], similarities[0][i]) for i in sorted_indices]


In [ ]:
ranked_documents


[('Efficient keyword extraction enhances search accuracy.', 0.75214136),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481666),
 ('Understanding document structure aids in keyword extraction.', 0.6316118),
 ('Document analysis involves extracting keywords.', 0.5675695),
 ('Semantic similarity improves document retrieval performance.', 0.550352),
 ('Keywords are important for keyword-based search.', 0.4580228),
 ('Keyword-based search relies on sparse embeddings.', 0.441233),
 ('This is a list which containing sample documents.', 0.16948149)]

In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:
print("Ranked Documents:")
for rank, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Ranked Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521413564682007
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448166608810425
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6316118240356445
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675694942474365
Rank 5: Document - 'Semantic similarity improves document retrieval performance.', Similarity Score - 0.5503519773483276
Rank 6: Document - 'Keywords are important for keyword-based search.', Similarity Score - 0.458022803068161
Rank 7: Document - 'Keyword-based search relies on sparse embeddings.', Similarity Score - 0.4412330090999603
Rank 8: Document - 'This is a list which containing sample documents.', Similarity Score - 0.16948148608207703


In [ ]:
print("Top 4 Documents:")
for rank, (document, similarity) in enumerate(ranked_documents[:4], start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.7521413564682007
Rank 2: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.7448166608810425
Rank 3: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.6316118240356445
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.5675694942474365


In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:
!pip install rank_bm25


In [ ]:
from rank_bm25 import BM25Okapi


In [ ]:
top_4_documents = [doc[0] for doc in ranked_documents[:4]]


In [ ]:
top_4_documents


['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [ ]:
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]


In [ ]:
tokenized_top_4_documents


[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'],
 ['Machine',
  'learning',
  'algorithms',
  'can',
  'optimize',
  'keyword',
  'extraction',
  'methods.'],
 ['Understanding',
  'document',
  'structure',
  'aids',
  'in',
  'keyword',
  'extraction.'],
 ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]

In [ ]:
tokenized_query = query.split()


In [ ]:
tokenized_query


['Natural',
 'language',
 'processing',
 'techniques',
 'enhance',
 'keyword',
 'extraction',
 'efficiency.']

In [ ]:
bm25=BM25Okapi(tokenized_top_4_documents)


In [ ]:
bm25


In [ ]:
bm25_scores = bm25.get_scores(tokenized_query)


In [ ]:
bm25_scores


array([0.1907998 , 0.16686672, 0.17803252, 0.        ])

In [ ]:
sorted_indices2 = np.argsort(bm25_scores)[::-1]


In [ ]:
sorted_indices2


array([0, 2, 1, 3])

In [ ]:
top_4_documents


['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:
reranked_documents = [(top_4_documents[i], bm25_scores[i]) for i in sorted_indices2]


In [ ]:
reranked_documents


[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [ ]:
print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")


Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


In [ ]:
ranked_documents[:4]


[('Efficient keyword extraction enhances search accuracy.', 0.75214136),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.74481666),
 ('Understanding document structure aids in keyword extraction.', 0.6316118),
 ('Document analysis involves extracting keywords.', 0.5675695)]

<h1>Cross-Encoder</h1>

In [ ]:
from sentence_transformers import CrossEncoder


In [ ]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')


config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
top_4_documents


['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:
pairs = []
for doc in top_4_documents:
    pairs.append([query, doc])

In [ ]:
pairs


[['Natural language processing techniques enhance keyword extraction efficiency.',
  'Efficient keyword extraction enhances search accuracy.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Machine learning algorithms can optimize keyword extraction methods.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Understanding document structure aids in keyword extraction.'],
 ['Natural language processing techniques enhance keyword extraction efficiency.',
  'Document analysis involves extracting keywords.']]

In [ ]:

scores = cross_encoder.predict(pairs)
scores

array([ 3.137871 ,  0.8421656, -2.9193   , -2.8781917], dtype=float32)

In [ ]:
scored_docs = zip(scores, top_4_documents)


In [ ]:
scored_docs


In [ ]:
reranked_document_cross_encoder = sorted(scored_docs, reverse=True)


In [ ]:
reranked_document_cross_encoder


[(3.137871, 'Efficient keyword extraction enhances search accuracy.'),
 (0.8421656,
  'Machine learning algorithms can optimize keyword extraction methods.'),
 (-2.8781917, 'Document analysis involves extracting keywords.'),
 (-2.9193, 'Understanding document structure aids in keyword extraction.')]

<h1>BM25</h1>

In [ ]:
reranked_documents


[('Efficient keyword extraction enhances search accuracy.',
  0.19079979534096053),
 ('Understanding document structure aids in keyword extraction.',
  0.1780325227902643),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  0.1668667199671815),
 ('Document analysis involves extracting keywords.', 0.0)]

In [ ]:
!pip install cohere


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.8/207.8 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 48.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 68.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.2 MB/s eta 0:00:00


In [ ]:
import cohere


/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)


In [ ]:
co = cohere.Client("nbDqU1hTVxWmXGbLYI6OnYhp4Cx40MZ5hOmO5oKX")


In [ ]:
top_4_documents


['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [ ]:
query


'Natural language processing techniques enhance keyword extraction efficiency.'

In [ ]:

response = co.rerank(
    model="rerank-english-v3.0",
    query="Natural language processing techniques enhance keyword extraction efficiency.",
    documents=top_4_documents,
    return_documents=True
)

In [ ]:
print(response)


id='83443384-f26c-4c1f-9381-12884faf4085' results=[RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Efficient keyword extraction enhances search accuracy.'), index=0, relevance_score=0.99411184), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Machine learning algorithms can optimize keyword extraction methods.'), index=1, relevance_score=0.9129032), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Understanding document structure aids in keyword extraction.'), index=2, relevance_score=0.32885265), RerankResponseResultsItem(document=RerankResponseResultsItemDocument(text='Document analysis involves extracting keywords.'), index=3, relevance_score=0.02865267)] meta=ApiMeta(api_version=ApiMetaApiVersion(version='1', is_deprecated=None, is_experimental=None), billed_units=ApiMetaBilledUnits(input_tokens=None, output_tokens=None, search_units=1.0, classifications=None), tokens=None, warnings=None)


In [ ]:
response.results[0].document.text


'Efficient keyword extraction enhances search accuracy.'

In [ ]:
response.results[0].relevance_score


0.99411184

In [ ]:

for i in range(4):
  print(f'text: {response.results[i].document.text} score: {response.results[i].relevance_score}')


text: Efficient keyword extraction enhances search accuracy. score: 0.99411184
text: Machine learning algorithms can optimize keyword extraction methods. score: 0.9129032
text: Understanding document structure aids in keyword extraction. score: 0.32885265
text: Document analysis involves extracting keywords. score: 0.02865267
